from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import Dict, Any, List
from pydantic import BaseModel
import re

from app.core.database import get_db
from app.models.resource import Resource

router = APIRouter(
    prefix="/jarvis",
    tags=["jarvis-agent"],
)

from app.core.agent import JarvisAgent

from typing import Dict, Any, List, Optional

class ChatRequest(BaseModel):
    query: str
    history: List[Dict[str, Any]] = []
    state: str = "IDLE"
    actionData: Optional[Dict[str, Any]] = None

from fastapi.responses import StreamingResponse
import json

@router.post("/chat")
async def process_chat(request: ChatRequest, db: Session = Depends(get_db)):
    """
    Agent / Tool Layer logic.
    Streams Server-Sent Events (SSE) generated by the JarvisAgent.
    """
    agent = JarvisAgent(db)
    
    async def sse_generator():
        try:
            async for event in agent.stream_chat(
                query=request.query, 
                history=request.history,
                pending_state=request.state,
                action_data=request.actionData
            ):
                yield f"data: {json.dumps(event)}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'content': str(e)})}\n\n"

    return StreamingResponse(sse_generator(), media_type="text/event-stream")

